services:
  api:
    build: 
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=app:secret@tcp(db)/demo_db
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 2s