services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: myapi:2.0
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mongo:7.0.12-jammy
    ports:
      - "27017:27017"
    # add health check of mongodb 7 in docker with mongosh
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5